# Use root/example as user/password credentials
version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGODB_DATABASE: nest-pokemon
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db